### PR TITLE
Fix some still present bugs and make a few changes - also new language "ru_ru.json".

### PR DESCRIPTION
**Pull request by DDaMAGEr**
Mars Ice Shard Ore
Mars Ice Spikes - ore generation under it

"ru_ru.json" language file for post-USSR users since Minecraft is pretty popular there (my post-USSR friend translated it, I converted to /u0xxx symbols).

Glacio Orbit - make Glacio show underneath instead of Mars

Slabs from extraterrestial bricks - make them drop 2x slab when double slab is broken.

netherite space suit material - swap places armor value from suit and pants (like in normal netherite armor)

request - glow lichen in Glacio Caves
request - coal lantern - produce 4 of these from coal, stick and paper instead of 1.

edit:
request - moglers fire immune (ModInit)

### CODE REVIEW

**Comment by MrScautHD** [comment]
In yor Translation is u0442\u043e\u043f\u043b\u0438\u0432\u0430

**Comment by MrScautHD** [comment]
Pls convert it too the normal back

**Comment by MrScautHD** [comment]
And very good work, i see im often brain afk 😂😅

**Comment by MrScautHD** [comment]
And for a Translation need i your dc tag, because if we has updates or sonething that you update your language too

**Comment by DDaMAGEr** [comment]
> And for a Translation need i your dc tag, because if we has updates or sonething that you update your language too.
Well, l sent it to your discord address.

**Pull request merged**
