### PR TITLE
Port Capability to 1.18

### PR DESCRIPTION
**Pull request by gisellevonbingen**

### CODE REVIEW

**Comment by MrScautHD** [comment]
is this pr done?

**Comment by gisellevonbingen** [comment]
done partially
it ok merge, then i create new pr after other done

**Comment by MrScautHD** [comment]
its ok i merge it if you done

**Comment by MrScautHD** [comment]
Btw on the forge discord gives a bot that say you the new mappings with "!mcp -c moj TileEntity" example here is it BlockEntity

**Comment by MrScautHD** [comment]
https://discord.gg/forge

**Comment by gisellevonbingen** [comment]
oh, so thanks

**Comment by gisellevonbingen** [comment]
it done now,
later i will create new pr
maybe it will be port about machines, block entities

**Comment by MrScautHD** [comment]
oh JEI for 1.18 is released if you rework the machines can you add it also? i think is not many work Jei changed not many

**Pull request merged**
