### PR TITLE
CraftTweaker Compatibility

### PR DESCRIPTION
**Pull request by gisellevonbingen**
## Summary

Even this pr is not merged,  modpack devs can add own recipe though addJSONRecipe
Like this
```js
<recipetype:beyond_earth:fuel_refining>.addJsonRecipe("test", {
   "type":"beyond_earth:fuel_refinery",
   "input":{
      "tag":"minecraft:water",
      "amount":2
   },
   "output":{
      "name":"beyond_earth:fuel",
      "amount":2
   }
});
```

This pr will help just more easy for add recipe

## Todo list

- [x] Compressing
- [x] Coal Generating
- [x] Fuel Refining
- [x] Oxygen Loading
- [x] Oxygen Bubble Distributing
- [x] NASA Workbenching
- [x] Alien Trades
- [x] Space Station

### CODE REVIEW

**Comment by gisellevonbingen** [comment]
# Compressing

## Example
```zs
<recipetype:beyond_earth:compressing>.addRecipe("compressing_test_1", <item:minecraft:diamond>, <tag:items:minecraft:coals>);

<recipetype:beyond_earth:compressing>.addRecipe("compressing_test_2", <item:beyond_earth:compressed_steel>, <tag:items:forge:nuggets/steel>, 50);

<recipetype:beyond_earth:compressing>.removeByName("beyond_earth:compressing/compressed_steel");
```
image

## Syntax

### addRecipe (1)
cookTime is use default value (200 ticks)

|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|IItemStack|output item stack|
|3|input|IIngredient|input ingredient|

### addRecipe (2)
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|IItemStack|output item stack|
|3|input|IIngredient|input ingredient|
|4|cookTime|int|process time [ticks]|

**Comment by gisellevonbingen** [comment]
# Coal Generating

## Example

```zs
<recipetype:beyond_earth:coal_generating>.addRecipe("coal_generating_test_1", 1998, <item:minecraft:lava_bucket>);

<recipetype:beyond_earth:coal_generating>.removeByName("beyond_earth:coal_generating/coal_block");
```
image

## Syntax

### addRecipe
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|burnTime|int|generating duration|
|3|input|IIngredient|input ingredient|

**Comment by gisellevonbingen** [comment]
# Fuel Refining

## Example

```zs
<recipetype:beyond_earth:fuel_refining>.addRecipe("fuel_refining_test_1", <fluid:beyond_earth:fuel> * 3, <fluid:minecraft:lava> * 5);

<recipetype:beyond_earth:fuel_refining>.addRecipe("fuel_refining_test_2", <fluid:beyond_earth:fuel> * 5, <tag:fluids:tconstruct:slime> * 3);

<recipetype:beyond_earth:fuel_refining>.removeByName("beyond_earth:fuel_refining/fuel_from_curde_oil");
```
image

## Syntax

### addRecipe 
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|IFluidStack|output fluid stack|
|3|input|IFluidStack<br>or CTFluidIngredient<br>or Many<KnownTag< Fluid>><br>or KnownTag< Fluid>|input fluid ingredient|

**Comment by gisellevonbingen** [comment]
# Oxygen Loading / Oxygen Bubble Distributing

## Example 1
```zs
<recipetype:beyond_earth:oxygen_loading>.addRecipe("oxygen_loading_test_1", 25, <tag:fluids:forge:milk> * 5);

<recipetype:beyond_earth:oxygen_bubble_distributing>.addRecipe("oxygen_loading_test_2", 20, <tag:fluids:forge:milk>);
```
image

## Example 2 : Add Loading/Distributing recipe in one line
```zs
<recipetype:beyond_earth:oxygen_loading>.addRecipePair("oxygen_loading_test_3", 5, <tag:fluids:minecraft:lava> * 2);
// same with this
//<recipetype:beyond_earth:oxygen_bubble_distributing>.addRecipePair("oxygen_loading_test_3", 5, <tag:fluids:minecraft:lava> * 2);
```
image

## Syntax 1

### addRecipe
add each manager's recipe (loading or distributing)
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|int|output oxygen amount|
|3|input|IFluidStack<br>or CTFluidIngredient<br>or Many<KnownTag< Fluid>><br>or KnownTag< Fluid>|input fluid ingredient|

## Syntax2
### addRecipePair
this method will add loading/distributing recipes using same input at once
defaultly, bubble distributing's oxygen is 4 times of loading
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|int|output oxygen amount|
|3|input|IFluidStack<br>or CTFluidIngredient<br>or Many<KnownTag< Fluid>><br>or KnownTag< Fluid>|input fluid ingredient|

## Syntax3
### addRecipePair
this method will add loading/distributing recipes using same input at once
set oxygen output amount each recipes
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|loading oxygen|int|oxygen loading's output oxygen|
|3|distributing oxygen|int|oxygen bubble distriubting's output oxygen|
|4|input|IFluidStack<br>or CTFluidIngredient<br>or Many<KnownTag< Fluid>><br>or KnownTag< Fluid>|input fluid ingredient|

Example
```zs
<recipetype:beyond_earth:oxygen_loading>.addRecipePair("oxygen_loading_test_3", 5, 20, <tag:fluids:minecraft:lava> * 2);
```

**Comment by gisellevonbingen** [comment]
# NASA Workbenching

## Example 1

```zs
<recipetype:beyond_earth:nasa_workbenching>.addRecipe("nasa_workbenching_test_1", <item:minecraft:beetroot_soup>, {
	<rocket_part:beyond_earth:body>  : [<item:minecraft:beetroot>, <item:minecraft:beetroot>, <item:minecraft:beetroot>, <item:minecraft:beetroot>, <item:minecraft:beetroot>, <item:minecraft:beetroot>],
	<rocket_part:beyond_earth:engine>: [<item:minecraft:bowl>]
});
```
image

### Example 2
```zs
<recipetype:beyond_earth:nasa_workbenching>.addRecipe("nasa_workbenching_test_2", <item:beyond_earth:rocket_t1>, {
	<rocket_part:beyond_earth:nose>     : [<item:beyond_earth:rocket_nose_cone>],
	<rocket_part:beyond_earth:body>     : [<item:minecraft:potato>, <item:minecraft:potato>, <item:minecraft:potato>, <item:minecraft:potato>, <item:minecraft:potato>, <item:minecraft:potato>],
	<rocket_part:beyond_earth:tank>     : [<item:minecraft:baked_potato>, <item:minecraft:baked_potato>],
	<rocket_part:beyond_earth:fin_left> : [<item:beyond_earth:rocket_fin>],
	<rocket_part:beyond_earth:fin_right>: [<item:beyond_earth:rocket_fin>],
	<rocket_part:beyond_earth:engine>   : [<item:minecraft:furnace>]
});
```
image

## Rocket Parts

These rocket parts are Beyond Earth's built-in parts

|order|name|with bracket|
|-|-|-|
|1|beyond_earth:nose|<rocket_part:beyond_earth:nose>|
|2|beyond_earth:body|<rocket_part:beyond_earth:body>|
|3|beyond_earth:tank|<rocket_part:beyond_earth:tank>|
|4|beyond_earth:fin_left|<rocket_part:beyond_earth:fin_left>|
|5|beyond_earth:fin_right|<rocket_part:beyond_earth:fin_right>|
|6|beyond_earth:engine|<rocket_part:beyond_earth:engine>|

image

Other mods can register own Rocket Part
But NASA Workbench is use their 6 part only
Each part's slots are placed left to right, up to down


## Syntax

### addRecipe 
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|output|IItemStack|output item stack|
|3|input|RocketPart[IIngredient[]]|input items with rocket part|

* rocket part and items are can skippable
* see example

**Comment by gisellevonbingen** [comment]
# Space Station

## Example

```zs
<recipetype:beyond_earth:space_station>.setRecipe([
	<tag:items:forge:storage_blocks/iron> * 5, 
	<item:minecraft:diamond_block> * 3, 
	<item:beyond_earth:nasa_workbench>
]);
```
image

## Note

Space Station's recipe is always exist only 1
So, please don't remove recipes,
If you want change recipe, just call 'setRecipe'

## Syntax

### setRecipe 
|order|name|type|value|
|-|-|-|-|
|1|input|IIngredient<br>or IIngredientWithAmount<br>or Many<KnownTag< Item>><br>or KnownTag< Item>|input item ingredients|

**Comment by gisellevonbingen** [comment]
# Alien Trading

## Example for remove

```zs
beyond_earth_alien_trading.removeAll();

beyond_earth_alien_trading.removeByJob("minecraft:fletcher");

beyond_earth_alien_trading.removeByJob(<profession:minecraft:butcher>);

beyond_earth_alien_trading.removeByJobWithLevel("minecraft:toolsmith", 1);

beyond_earth_alien_trading.removeByJobWithLevel(<profession:minecraft:armorer>, 2);
```

## Example for add

```zs
beyond_earth_alien_trading.addJsonRecipe("alien_trading_test_1", {
	"type": "beyond_earth:alien_trading_itemstack",
	"job": "minecraft:fletcher",
	"level": 1,
	"xp": 1,
	"costA": { "item": "minecraft:emerald" },
	"result": { "item": "minecraft:arrow", "count": 16 }
});

beyond_earth_alien_trading.addJsonRecipe("alien_trading_test_2", {
	"type": "beyond_earth:alien_trading_itemstack",
	"job": <profession:minecraft:cleric>.registryName,
	"level": 1,
	"xp": 1,
	"costA": { "item": <item:minecraft:diamond>.registryName },
	"result": { "item": "minecraft:emerald" }
});
```
## Syntax

### addRecipe 
|order|name|type|value|
|-|-|-|-|
|1|name|String|recipe name|
|2|json|MapData|trading json data*|

* see detail to here https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/wiki/Alien-Trade-Recipes
* @MrScautHD , plz copy this document to Beyond Earth Wiki and do modpack dev can see it
* copy from here https://gist.githubusercontent.com/gisellevonbingen/5ea8fcfaaae76507c05e19ad20db07ef/raw/6b6361aec377c58a9001318f605c68634453cf3f/Alien-Trade-Recipes
* boss_tools -> beyond_earth

**Comment by gisellevonbingen** [comment]
this pr is ready
please review in turn

**Comment by MrScautHD** [comment]
Beyond Earth Wiki can everyone send things in it

**Comment by MrScautHD** [comment]
done?

**Comment by gisellevonbingen** [comment]
yes

**Pull request merged**
