### PR TITLE
space station recipe

### PR DESCRIPTION
**Pull request by gisellevonbingen**
1. create space station recipe
1. only can use 'beyond_earth:space_station/space_station.json' file
1. replace to use recipe (with cleanup)
1. require recipe icon

image
image

### CODE REVIEW

**Comment by MrScautHD** [comment]
its good but pls make for every rocket a new JEI category (it is wierd just with one)

**Comment by gisellevonbingen** [comment]
that is not rocket recipe, rocket is temp icon (require change to other, but i can't make icon)

**Comment by MrScautHD** [comment]
> that is not rocket recipe, rocket is temp icon

so what does you use then for it?

**Comment by gisellevonbingen** [comment]
space station can create on space,
that rockets in left for show  'use rocket for create space station'
like recipe for 'machine'

**Comment by MrScautHD** [comment]
> space station can create on space, that rockets in left for show 'use rocket for create space station' like recipe for 'machine'

can you give ma screenshot

**Comment by gisellevonbingen** [comment]
left rockets? or recipe for machines?

**Comment by gisellevonbingen** [comment]
image

**Comment by MrScautHD** [comment]
but that you see the recpies need you click on the rocket sure?

**Comment by gisellevonbingen** [comment]
but if create 'space station' category to every rocket,
rocket category count reach to 8, too many

my idea
1. remove catalysts at space station category (left rockets)
2. or integration to each rocket's fuel loading recipe

**Comment by gisellevonbingen** [comment]
idea 2 will looks like this (tier 1, tier 2 tier 3, tier 4 each)
not commit yet
image
image

(maximize 1920x1080)
image

reduce recipe height when for show 'Fuel Loading', 'Space Station' recipes at one time
image

**Comment by MrScautHD** [comment]
that is to many, maybe just remove it (its not really good posible to make a JEI for it (what if the list longer 6...))

**Comment by MrScautHD** [comment]
(just remove the JEI Support and the other thing we adding)

**Comment by gisellevonbingen** [comment]
fixed
slots count is flexible at recipe's ingredients counts

image

**Comment by MrScautHD** [comment]
mhhh, i like it how it works, but how it looks right now is not really good, 1 make a new category for every rocket, 2 remove the text, 3 just name the title then Space Station

**Comment by gisellevonbingen** [comment]
what mean 'new category for every rocket'
is different with this?
image
(be remove text, change icon)

**Comment by MrScautHD** [comment]
yep that is what i mean then need you do it also not for every rocket because it is the space station recpie!

**Comment by gisellevonbingen** [comment]
then. if remove text, change icon in that picture (with hide empty slot)
is ok?

**Comment by MrScautHD** [comment]
yep then is it amazing xD

**Comment by MrScautHD** [comment]
and place the slot pls in the middle if that possible

**Comment by gisellevonbingen** [comment]
ok i will try

**Comment by gisellevonbingen** [comment]
i think text exist is better
otherwise content is too few
image

**Comment by MrScautHD** [comment]
yea ok then change the icon and you are done. (good work)

**Comment by gisellevonbingen** [comment]
has you idea for icon?
can't find appropriate icon,
how about create a new icon for space station?

**Comment by MrScautHD** [comment]
> has you idea for icon? can't find appropriate icon, how about create a new icon for space station?

just place a, place holder texture in it (my texturer team make one)

**Comment by gisellevonbingen** [comment]
done it 
image

can replace icon from assets.beyond_earth.textures.jei.space_station_jei.png

**Comment by MrScautHD** [comment]
pls dont add the placer holder texture to the background texture

**Comment by gisellevonbingen** [comment]
ok it done

**Comment by gisellevonbingen** [comment]
> pls dont add the placer holder texture to the background texture

this is not weird
JEI texture file require 256x256
that is icon.png file is too

and for reduce texture bind in openGL (drawcall)
can include background, icon in same file

**Comment by gisellevonbingen** [comment]
oh, wait
i found solution

**Comment by gisellevonbingen** [comment]
it done

**Comment by MrScautHD** [comment]
> it done

good work i merge it after i done with the 6.1 basics

**Pull request merged**
