### PR TITLE
Add Advancements

### PR DESCRIPTION
**Pull request by gisellevonbingen**
image

1. Craft a NASA Workbench
2. Craft space suit(pant, boots, mask)
3. Craft a Tier 1 Rocket
4. Entered to Moon
5. Trade with alien
6. Place flag on Moon
7. Create space station
8. Throw item to out of orbit (a.k.a. Space debris)
9. Craft Tier 2 Rocket
10. Entered to Mars
11. Plating potatoes on Mars (did you see movie Martian?)
11. Craft netherite space suit set
12. Craft Tier 3 Rocket
13. Enter to Mercury, Venus
14. Craft Tier 4 Rocket
15. Entered to Glacio

### CODE REVIEW

**Comment by MrScautHD** [comment]
if (level.isClientSide() == true) {...
pls clean up the code a bit

**Comment by gisellevonbingen** [comment]
Done

**Comment by MrScautHD** [comment]
remove in generel == true

**Comment by gisellevonbingen** [comment]
ah, i saw it now
it fixed

**Comment by MrScautHD** [comment]
amazing!

**Pull request merged**
