### PR TITLE
1.18 api enhancement

### PR DESCRIPTION
**Pull request by gisellevonbingen**
### Changes

1. Add Events
2. Extract duplicated statements (IRocketItem, IRocketEntity)

### Events
1. RocketPlaceEvent : post when place rocket on launch pad
4. RocketPickResultEvent : wheel click on rocket
5. PlayerEnterPlanetSelectionEvent : rocket flying reach to y 600
6. PlayerExitPlanetSelectionEvent : player dead or player select destination on PlanetSelectionGUI (exact. cleanUpPlayerNBT)
7. PlayerLandingStartEvent : when player start riding lander
8. PlayerLandingResumeEvent : when player change riding lander (e.g. y under 0 in orbit)

### CODE REVIEW

**Comment by MrScautHD** [comment]
PlayerEnterPlanetSelectionEvent, PlayerExitPlanetSelectionEvent   (this events is useless you can just check if a player has opend the gui, with the ScreenEvent)

**Comment by MrScautHD** [comment]
For what is RocketPlaceEvent, RocketPickResultEvent, PlayerLandingResumeEvent  good?

PlayerLandingStartEvent is useless because you can just check if a player ride a lander

**Comment by gisellevonbingen** [comment]
> PlayerEnterPlanetSelectionEvent, PlayerExitPlanetSelectionEvent (this events is useless you can just check if a player has opend the gui, with the ScreenEvent)

For serverside,
Modder can set own PersistentData
Like this
>pass.getPersistentData().putBoolean(BeyondEarthMod.MODID + ":planet_selection_gui_open", true);

**Comment by gisellevonbingen** [comment]
> For what is RocketPlaceEvent, RocketPickResultEvent, PlayerLandingResumeEvent good?
> 
> PlayerLandingStartEvent is useless because you can just check if a player ride a lander

Can set modify Rocket, Item

EntityConstructEvent can know Rocket created
But can't know rocket is why, from who created,
RocketPlaceEvent can know it

**Comment by gisellevonbingen** [comment]
in PlayerLandingResumeEvent,
I know i can use player teleport event
but when that event called, player ride old lander yet
modder can't know new lander
It inform player was transferred

The important thing is that can know player was ride 'what' lander .
For example, you can copy the NBT you set on a previous lander to a new lander.

**Comment by gisellevonbingen** [comment]
Here is event's example
in this example, Keep custom name on rocket item up to the lander from when rocket place

```Java
public class Test {

	private static final String KEY = BeyondEarthMod.MODID + ":rocket_custom_name";

	@SubscribeEvent
	public static void onRocketPlace(RocketPlaceEvent event) {
		IRocketEntity rocket = event.getRocket();
		UseOnContext context = event.getUseOnContext();
		ItemStack item = context.getItemInHand();

		if (item.hasCustomHoverName() == true) {
			Component displayName = item.getHoverName();
			rocket.setCustomName(displayName);
		}
	}

	@SubscribeEvent
	public static void onRocketPickedResult(RocketPickResultEvent event) {
		IRocketEntity rocket = event.getRocket();
		ItemStack item = event.getItemStack();

		if (rocket.hasCustomName() == true) {
			Component customName = rocket.getName();
			item.setHoverName(customName);
		}
	}

	@SubscribeEvent
	public static void onPlayerEnterPlanetSelection(PlayerEnterPlanetSelectionEvent event) {
		Player player = event.getPlayer();
		IRocketEntity rocket = event.getRocket();

		if (rocket.hasCustomName() == true) {
			Component customName = rocket.getName();
			player.getPersistentData().putString(KEY, Component.Serializer.toJson(customName));
		}
	}

	@SubscribeEvent
	public static void onPlayerExitPlanetSelection(PlayerExitPlanetSelectionEvent event) {
		Player player = event.getPlayer();
		player.getPersistentData().remove(KEY);
	}

	@SubscribeEvent
	public static void onPlayerLandingStart(PlayerLandingStartEvent event) {
		Player player = event.getPlayer();
		LanderEntity lander = event.getLander();

		if (player.getPersistentData().contains(KEY)) {
			MutableComponent component = Component.Serializer.fromJson(player.getPersistentData().getString(KEY));
			ItemStack rocketItemStack = lander.getInventory().getStackInSlot(1);
			rocketItemStack.setHoverName(component);
		}
	}
}
```

**Comment by MrScautHD** [comment]
ah ok, sure i take laiter a look on it if i on pc

**Comment by MrScautHD** [comment]
i added the IRocket thing its cool! i just do it a bit other, by the events need i to look again what all they do and if no other way possible

**Comment by MrScautHD** [comment]
RocketPlaceEvent can you use too EntityJoinWorldEvent,
PlayerEnterPlanetSelectionEvent  can you use too ScreenInit and check if this screen Planet Slecetion GUI

**Comment by gisellevonbingen** [comment]
EntityJoinWorldEvent can't know who rocket placed (and what held item)

PlayerEnterPlanetSelectionEvent is serverside event
when reach y 600, rocket is discard and player is just hover
TickEvent can't know player was ride what rocket

**Comment by MrScautHD** [comment]
ahh maybe a agrument

**Comment by MrScautHD** [comment]
but i want to change a bit the events

**Comment by MrScautHD** [comment]
at this moment that you call the Event (is the old lander just null or not?)
MinecraftForge.EVENT_BUS.post(new PlayerLandingResumeEvent(player, lander, entityToSpawn));

**Comment by gisellevonbingen** [comment]
> at this moment that you call the Event (is the old lander just null or not?)
MinecraftForge.EVENT_BUS.post(new PlayerLandingResumeEvent(player, lander, entityToSpawn));

old lander removed in world
but still exist in memory

**Comment by MrScautHD** [comment]
are you sure?

**Comment by MrScautHD** [comment]
> > at this moment that you call the Event (is the old lander just null or not?)
> > MinecraftForge.EVENT_BUS.post(new PlayerLandingResumeEvent(player, lander, entityToSpawn));
> 
> old lander removed in world but still exist in memory

idk if you right so i do it like forge do it

**Comment by MrScautHD** [comment]
i add it manuel (i close it if i done)

**Comment by MrScautHD** [comment]
all added (maybe with other names) good work anyway!

**Pull request closed without merging**
