### PR TITLE
unify jei rocket recipe categories

### PR DESCRIPTION
**Pull request by gisellevonbingen**
1. unify to one category each rocket's fuel loading recipes

image
image
image
image

### CODE REVIEW

**Comment by MrScautHD** [comment]
thats cool but maybe remove the slot with the rocket in it ( its wierd)

**Comment by gisellevonbingen** [comment]
previous category show rocket item as catalyst

but unified category doesn't show catalysts
each rocket items don't show in unified category

so, i added rocket item to recipe for split each rocket's fuel loading recipes and for show rocket's fuel capacity
because each rocket's fuel capacity is different

or, how about unify rocket recipes ?
there 4 recipes currently
then require show rocket's fuel capacity on other gui

**Comment by MrScautHD** [comment]
you changed it to just 1, its a good idea because the code looks cleaner but the category icon has also the false item so it is better to change it to 4 categorys or try to fix that without the slot

**Comment by gisellevonbingen** [comment]
you mean like this?
image

**Comment by MrScautHD** [comment]
yea that this good! (if it work correctly)

**Comment by gisellevonbingen** [comment]
and i add tooltip in rocket, rover fluid tank
click to show fuel recipe
try it out
image
image

**Comment by MrScautHD** [comment]
good idea too!

**Comment by MrScautHD** [comment]
is it done to merge?

**Comment by gisellevonbingen** [comment]
yes it ready

**Comment by MrScautHD** [comment]
has you changed any on the ModInit? (that i sure i brake not my Pr)

**Comment by gisellevonbingen** [comment]
no hasn't

**Pull request merged**
