### PR TITLE
cleanup PlanetSelectionGUI

### PR DESCRIPTION
**Pull request by gisellevonbingen**
1. use dimension key instead of integer
2. use boolean for create space station

### CODE REVIEW

**Comment by MrScautHD** [comment]
that need to many performance to make a new Resoruce Key

**Comment by MrScautHD** [comment]
2. you seted it instand to default if you click on a button that brake the system of the red buttons

**Comment by gisellevonbingen** [comment]
this isn't called in every ticks
in dynamically program, must create ResourceKey once somewhere
It's cumbersome to add an if every time a planet/moon is added for a bit of performance

can you comment more detail about 'you seted it instand to default if you click on a button that brake the system of the red buttons'?

**Comment by MrScautHD** [comment]
you set the Default things instand if you press on any button, also on red ones, and that is a problem

**Comment by gisellevonbingen** [comment]
is you mean 'defaultOptions(context.getSender());' ?

**Comment by MrScautHD** [comment]
i mean you can also click on buttons that are red, so the default thing are used

**Comment by gisellevonbingen** [comment]
you mean, if click this red button,
defaultOptions to player?
image

**Comment by MrScautHD** [comment]
is it not?

**Comment by MrScautHD** [comment]
> this isn't called in every ticks in dynamically program, must create ResourceKey once somewhere It's cumbersome to add an if every time a planet/moon is added for a bit of performance
> 
> can you comment more detail about 'you seted it instand to default if you click on a button that brake the system of the red buttons'?

 It's cumbersome to add an if every time a planet/moon is added for a bit of performance

but i think the server delete it after this not anymore (i thinked also not that this need so many performance but it does)

**Comment by gisellevonbingen** [comment]
https://github.com/MrScautHD/Beyond-Earth/pull/57/files#diff-cef528e519cd082f5fdd141215afc08e8fca905968f47de47ffdbbb2b72b2428R654

exist if statement at 'addSpaceStationImageButton'
that condition is 'this.spaceStationItemList' (check for space station ingredients)

**Comment by MrScautHD** [comment]
ohh i forgoten this, yea then is it fine

**Comment by MrScautHD** [comment]
can you maybe try a system that not make a new key? like just use it from Methods

**Comment by MrScautHD** [comment]
you call already the Methode thing can you give it him not instandly (without make a new key)

**Comment by gisellevonbingen** [comment]
> It's cumbersome to add an if every time a planet/moon is added for a bit of performance
> 
> but i think the server delete it after this not anymore (i thinked also not that this need so many performance but it does)

because of this? #23 
ResourceKey.create 's internal code is bellow
just make string and access hashmap
that's not expensive call
image

#23 's problem is so many call 'ResourceKey.create' in 'every ticks' about 'all entities'
but planet selection is once when player click
don't be worry for performance

but if you want, i'm gladly do it
i have some idea

**Comment by MrScautHD** [comment]
nahh i think its better you find a other way

**Comment by gisellevonbingen** [comment]
it changed
ResourceKey.create be called once and use cached instance by ResourceKey

**Comment by MrScautHD** [comment]
ehhhh, i will take a look on it

**Pull request closed without merging**
