### PR TITLE
Add zh_cn.json

### PR DESCRIPTION
**Pull request by Mai-xiyu**
The mod's Chinese.json/lang

### CODE REVIEW

**Comment by Mai-xiyu** [comment]
[zh_cn.zip](https://github.com/MrScautHD/Beyond-Earth/files/9758401/zh_cn.zip)

**Comment by MrScautHD** [comment]
pls just the lang file

**Comment by Mai-xiyu** [comment]
nope sry i can't now&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 16, 2022 00:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MrScautHD/Beyond-Earth] Add zh_cn.json (PR #186)




 
pls just the lang file

**Comment by Mai-xiyu** [comment]
I see that someone has already created zh_cn.json for a pull request, and I don't think it's needed




哈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MrScautHD/Beyond-Earth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月16日(星期天) 凌晨0:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MrScautHD/Beyond-Earth] Add zh_cn.json (PR #186)





 
pls just the lang file

**Pull request closed without merging**
