### PR TITLE
alien trade recipes

### PR DESCRIPTION
**Pull request by gisellevonbingen**
idea from https://discord.com/channels/698598471896268931/813489898538926091/923551188027330560

1. remove previous trade items (copied from vanilla)
2. instead, declare alien trade recipe
3. add trade json files with same previous trades

image

finally, modpack can create own alien trades

image

### CODE REVIEW

**Comment by MrScautHD** [comment]
this system is amazing!

**Comment by gisellevonbingen** [comment]
Could you please check if there is anything strange in the trade items?
There are too many json files, I may have made a mistake

**Comment by MrScautHD** [comment]
yep i check it before i merge it, i will do that in 1-2 hours because i search my phone now :D

**Comment by gisellevonbingen** [comment]
in example

image

**Comment by MrScautHD** [comment]
btw are this recpie unltimated or does the alien block it if the player buy to many?

**Comment by MrScautHD** [comment]
i think aliens can not restock because they don't have a owner block (but i check that laiter too)

**Comment by gisellevonbingen** [comment]
As per the previous code, transactions are unlimited
If aliens can restock, I think it's fine to limit it.
https://github.com/MrScautHD/Beyond-Earth/pull/25/files#diff-6adfaad44c2c818ad958734820dc58013cc633054eb3f259e9147c4daab9ef33R32

MAX_USES is 9999

it can override from json

**Comment by gisellevonbingen** [comment]
i know aliens not restock too

**Comment by gisellevonbingen** [comment]
I made json wiki (require boss_tools_giselle_addon -> beyond_earth)
Preview : https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/wiki/Alien-Trade-Recipes
Raw : https://gist.github.com/gisellevonbingen/5ea8fcfaaae76507c05e19ad20db07ef

**Comment by MrScautHD** [comment]
Pls Fix the conflicts

**Comment by gisellevonbingen** [comment]
it done

**Comment by MrScautHD** [comment]
Good work!

**Pull request merged**
