### PR TITLE
Add Patchouli Books from book of Kraaven (WIP)

### PR DESCRIPTION
**Pull request by TathanDev**
You should add a Patchouli books to Beyond Earth because, i saw a lot of people in the discord asking about machines, and a lot of thing that can be added in a patchouli book.

For the moment, i don't finish the books and i have some errors to fix.

PS : There are two commits named Update build.gradle, just ignore them^^

### CODE REVIEW

**Comment by MrScautHD** [comment]
does it works fine for 1.19?

**Comment by TathanDev** [comment]
For the moment, i launch the game, i have the book and i can open it.
But there is an errors with book : there are no entries/categories

**Comment by MrScautHD** [comment]
i take then a look

**Comment by TathanDev** [comment]
I finish the patchouli integration if you want to take a look

**Comment by MrScautHD** [comment]
why did you close it?

**Comment by TathanDev** [comment]
I don"t know !

**Pull request closed without merging**
