### PR TITLE
add fuel full items in creative tab

### PR DESCRIPTION
**Pull request by gisellevonbingen**
1. same with #41 
1. just changed whitespace

image

### CODE REVIEW

**Comment by MrScautHD** [comment]
is it ok if i do that by my self and i sort it then cool?

**Comment by gisellevonbingen** [comment]
> is it ok if i do that by my self and i sort it then cool?

about SpaceSuit?

**Comment by MrScautHD** [comment]
i mean the full items without a good sorting looks wierd

**Comment by gisellevonbingen** [comment]
maybe translator is weird
can you sort items youself?

**Comment by MrScautHD** [comment]
i mean, can i do the sorting?

**Comment by gisellevonbingen** [comment]
ah you mean 'sorting' is

change order this items?
image

**Comment by MrScautHD** [comment]
yep

**Comment by gisellevonbingen** [comment]
now can change items order youself

reference this
https://github.com/MrScautHD/Beyond-Earth/pull/45/commits/87c9e84a2d14eac44529b9733851fa819e1e5c52#diff-cde14035527022b07ccfbdf2d42f91bf68e1af74212e5be7b9c42c87b5fc0404R22

**Comment by MrScautHD** [comment]
i merge it after i done with the 6.1 basics

this is my changelog right now(that you know how long that can took...):
Make a Own Oxygen System to disable Conflicts (6.1) ❌ 
Energy Cable (6.1) ❌ 
Change to extend from Entity (6.1) ❌ (Vehicle Class)
Add Globes(6.1) ❌ 
Rover use to many fuel (6.1) ❌
Fix Ore gen is a to random gen (6.1) ❌ 
Add https://github.com/MrScautHD/Beyond-Earth/issues/43 ❌
Change Seed Fix to the Forge ones:  - 39.0.47 Expand the LevelStem codec to allow dimension jsons to specify that the dimension's chunk generator should use the overworld/server's seed (#7955) ❌
Fix  https://github.com/MrScautHD/Beyond-Earth/issues/46 ❌
Change baseTick to tick of Vehicles (for a lag free tick, change particle pos because it is so many smother) ❌ 
Fix armor duability (6.1) ❌ 
Rework iron plate id,recpie (6.1) ❌ 
Update to the newset Forge Version (6.1) ❌
Fix Space Suit Helmet if they enchanted is not rendering the enchanted thing (6.1) ✅ 
Fix can not enchant Space Suit (6.1) ✅ 
Fix Rocket rotation if they spawn (6.1) ❌
Add Explosion if the rocket crash with a block (6.1) ❌
Fix get damage if you teleport (6.1) ❌
Fix https://github.com/MrScautHD/Beyond-Earth/issues/48 (6.1) ❌
Add Vehicle Item (6.1) ❌
Fix Ore don't drop XP (6.1) ❌

**Comment by MrScautHD** [comment]
https://github.com/MrScautHD/Beyond-Earth/commit/0616a4e27490eabd8bf4b5f9e478a17df2b749a7

**Pull request closed without merging**
