### PR TITLE
fill oxygen/fuel full items to creactive tab

### PR DESCRIPTION
**Pull request by gisellevonbingen**
it will be useful for test

image
image

### CODE REVIEW

**Comment by MrScautHD** [comment]
do you know to make the sorting better? like you can place a air (nothing) block in the crative tab

**Comment by gisellevonbingen** [comment]
like this? (space suit is require rewrite code)
image

**Comment by MrScautHD** [comment]
yea how does this work?

**Comment by MrScautHD** [comment]
because with that can we a amazing sorting

**Comment by gisellevonbingen** [comment]
> yea how does this work?

add ItemStack.EMPTY
https://github.com/gisellevonbingen/Beyond-Earth/blob/a7fa00dbc9bfca71a568303a2af01c31d25b7b05/src/main/java/net/mrscauthd/beyond_earth/itemgroup/CreativeModeTabFillAltable.java#L28

and pr replaced to #45

**Comment by MrScautHD** [comment]
ah thx i understand (why you closed it)?

**Comment by gisellevonbingen** [comment]
replace to #45 
because of whitespace

**Pull request closed without merging**
